import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from "./components/navigation";
import styles from "./page.module.css";
import { RouteProvider } from "./contexts/RouteContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header className={styles.header}>
          <h1 className={styles.logo}>
            <img src="/img/micronav.svg" alt="Micronav (Alpha)" width={300} height={100} />
            <span>Alpha</span>
          </h1>
          {/* <Navigation /> */}
        </header>
        <main>
          <RouteProvider>
            {children}
          </RouteProvider>
        </main>
        <footer>
          <p className={styles.footerText}>Copyright 2025 - Micronav Alpha</p>
        </footer>
      </body>
    </html>
  );
}
